apiVersion: v1
kind: Service
metadata:
  name: {{ include "filestash.fullname" . }}
  labels:
    {{- include "filestash.labels" . | nindent 4 }}
    {{- include "filestash.componentLabels.webapp" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "filestash.selectorLabels" . | nindent 4 }}
    {{- include "filestash.componentLabels.webapp" . | nindent 4 }}
{{- if .Values.documentServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "filestash.documentServer.fullname" . }}
  labels:
    {{- include "filestash.labels" . | nindent 4 }}
    {{- include "filestash.componentLabels.documentServer" . | nindent 4 }}
spec:
  type: {{ .Values.documentServer.service.type }}
  ports:
    - port: {{ .Values.documentServer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "filestash.selectorLabels" . | nindent 4 }}
    {{- include "filestash.componentLabels.documentServer" . | nindent 4 }}
{{- end }}